[package]
name = "aoc-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
tokio = { version = "1.48.0", features = ["rt", "sync"] }
tokio-stream = "0.1.17"